name: ShigenUI
version: '1.0.0'
main: com.github.e2318501.shigenUI.ShigenUI
api-version: '1.21'
depend: [ Multiverse-Core ]
commands:
  shigen:
    aliases: [ sh ]
    description: Open a GUI
    usage: /<command>
